version: "3"
services:
  parking-mgmt-db:
    image: mongo:3.7-jessie
    ports:
      - "27017"
    networks:
      - backend

  parking-mgmt-be:
    image: codingmaniacs/parking-mgmt-be
    build:
      context: ./parking-mgmt-be
      dockerfile: Dockerfile
    ports:
      - 9000:9000
    networks:
      - frontend
      - backend
    depends_on:
      - parking-mgmt-db

  parking-mgmt-react:
    image: codingmaniacs/parking-mgmt-fe-react
    build:
      context: ./parking-mgmt-fe-react
      dockerfile: Dockerfile
    ports:
      - 8080:5000
    networks:
      - frontend
    depends_on:
      - parking-mgmt-be
  
  parking-mgmt-vue:
    image: codingmaniacs/parking-mgmt-fe-vue
    build:
      context: ./parking-mgmt-fe-vue
      dockerfile: Dockerfile
    ports:
      - 8181:80
    networks:
      - frontend
    depends_on:
      - parking-mgmt-be

networks:
  frontend:
  backend:

volumes:
  db-data: