version: "3"
services:
  parking-mgmt-db:
    image: mongo:3.7-jessie
    ports:
      - "27017"
    networks:
      - backend

  parking-mgmt-be:
    image: codingmaniacs/parking-mgmt-be
    build:
      context: ./parking-mgmt-be
      dockerfile: Dockerfile
    ports:
      - 9000:9000
    networks:
      - frontend
      - backend
    depends_on:
      - parking-mgmt-db

networks:
  backend:

volumes:
  db-data: